version: '3'
services:
  book-api-app:
    build: .
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定します。
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/backend
    command: bash -c 'cd backend && yarn dev'
    ports:
      - 8000:3000
    tty: true
